--- 
abstract: "a perl source filter to allow external configuration "
author: Gavin Carr <gavin@openfusion.com.au>
build_requires: 
  Cwd: 0
  File::Basename: 0
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Blosxom-Include
no_index: 
  directory: 
    - inc
    - t
requires: 
  FileHandle: 0
  Filter::Simple: 0
version: 0.001
